version : 1
formatters:
  simple:
    format: '%(asctime)s [%(name)s] %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
loggers:
  representation_data:
    level: DEBUG
    handlers:  []
    propagate: no
  reasoning_data:
    level: DEBUG
    handlers: []
    propagate: no
  segmentation_training:
    level: INFO
    handlers: []
    propagate: no
  vae_training:
    level: INFO
    handlers: []
    propagate: no
  to_popper:
    level: INFO
    handlers: []
    propagate: no
root:
  level: INFO
  handlers: [console]